# Generated by Django 4.0 on 2022-02-09 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_content',
            field=models.TextField(verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_image',
            field=models.ImageField(blank=True, null=True, upload_to='blog_images', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_title',
            field=models.CharField(max_length=250, verbose_name='Tilte'),
        ),
    ]
